version: "3.8"
services:
  app:
    image: bibichannel/laravel:v1
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - db
    networks:
      - backend
      - database

  db:
    image: postgres:alpine3.17
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: root
      POSTGRES_DB: project
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - database

  webserver:
    image: nginx:1.23.3-alpine
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - db
    networks:
      - frontend
      - backend
  
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - database

networks:
  frontend:
    name: frontend
    driver: bridge
  backend:
    name: backend
    driver: bridge
  database:
    name: database
    driver: bridge
